- hosts: localhost
  gather_facts: no

  tasks:
    - debug:
        msg: "Test if custom library is loaded"
    # Must use import instead of include; must be static loading of role!
    - import_role:
        name: custom_role
    - custom_module:
        name: 'hello world'


